# developed by "M.Shahjhan Gondal"

# Dataset of Model

In [27]:
faqs = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""

# Import Libraries

In [28]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [29]:
tokenizer = Tokenizer()

In [30]:
tokenizer.fit_on_texts([faqs])

In [31]:
tokenizer.word_index               # check numbers assign to words

{'the': 1,
 'you': 2,
 'i': 3,
 'to': 4,
 'a': 5,
 'of': 6,
 'is': 7,
 'have': 8,
 'will': 9,
 'can': 10,
 'what': 11,
 'course': 12,
 'program': 13,
 'in': 14,
 'for': 15,
 'all': 16,
 'sessions': 17,
 'on': 18,
 'be': 19,
 'and': 20,
 'this': 21,
 'if': 22,
 'am': 23,
 'pay': 24,
 'payment': 25,
 'make': 26,
 'we': 27,
 'do': 28,
 'subscription': 29,
 'where': 30,
 'rs': 31,
 'so': 32,
 'campusx': 33,
 'session': 34,
 'our': 35,
 'paid': 36,
 'join': 37,
 'able': 38,
 'your': 39,
 'website': 40,
 'placement': 41,
 'fee': 42,
 'data': 43,
 'monthly': 44,
 'month': 45,
 'not': 46,
 'get': 47,
 'yes': 48,
 'once': 49,
 'past': 50,
 'feb': 51,
 'assistance': 52,
 'science': 53,
 '7': 54,
 '5600': 55,
 'are': 56,
 'watch': 57,
 'google': 58,
 'by': 59,
 'com': 60,
 'mail': 61,
 'from': 62,
 'contact': 63,
 'us': 64,
 'at': 65,
 'or': 66,
 'doubt': 67,
 'mentorship': 68,
 'payments': 69,
 '799': 70,
 'total': 71,
 'duration': 72,
 'months': 73,
 'learning': 74,
 'case': 75,
 'here': 76,
 '

In [32]:
for sentences in faqs.split('\n'):        # split the dataset to sentences on basis of next line    
    print(sentences)

About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a sessi

# Assign numbers to words

In [33]:
# now on basis of old numbers,sentences are converting to numbers
input_sequence = []
for sentences in faqs.split('\n'):                                           # split the dataset to sentences on basis of next line 
    
    tokenized_sentence=tokenizer.texts_to_sequences([sentences])[0]          # to avoid double list [[93,1,13]], we use [0]
    #print(tokenized_sentence)

    for i in range(1, len(tokenized_sentence)):
            input_sequence.append(tokenized_sentence[:i+1])                #Example:  tokenized_sentence = ["I", "like", "to", "learn", "Python"].

                                                                                #    Iteration 1 (i=1): tokenized_sentence[:2] → ["I", "like"]

                                                                                 #   Iteration 2 (i=2): tokenized_sentence[:3] → ["I", "like", "to"]

                                                                                 #   Iteration 3 (i=3): tokenized_sentence[:4] → ["I", "like", "to", "learn"]

                                                                                  #  Iteration 4 (i=4): tokenized_sentence[:5] → ["I", "like", "to", "learn", "Python"]'''
            

In [34]:
input_sequence

[[93, 1],
 [93, 1, 13],
 [11, 7],
 [11, 7, 1],
 [11, 7, 1, 12],
 [11, 7, 1, 12, 42],
 [11, 7, 1, 12, 42, 15],
 [11, 7, 1, 12, 42, 15, 43],
 [11, 7, 1, 12, 42, 15, 43, 53],
 [11, 7, 1, 12, 42, 15, 43, 53, 68],
 [11, 7, 1, 12, 42, 15, 43, 53, 68, 13],
 [11, 7, 1, 12, 42, 15, 43, 53, 68, 13, 147],
 [11, 7, 1, 12, 42, 15, 43, 53, 68, 13, 147, 148],
 [1, 12],
 [1, 12, 94],
 [1, 12, 94, 5],
 [1, 12, 94, 5, 44],
 [1, 12, 94, 5, 44, 29],
 [1, 12, 94, 5, 44, 29, 95],
 [1, 12, 94, 5, 44, 29, 95, 30],
 [1, 12, 94, 5, 44, 29, 95, 30, 2],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6, 31],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6, 31, 70],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6

In [35]:
# now we will find the senetnce of maximum langth  bcz we need to set equal size of all inputs.
# find max length and zdd 0 padding to other all sentences to make size equal of all senetnces

#[len(x) for x in input_sequence]                         #  [len(x) for x in input_sequence check lenths of sentences
max_len = max([len(x) for x in input_sequence])        # We find the Max length of all  sequences
max_len

57

In [36]:
# Add  Zeros_padding by keras pad_sequences function
from  tensorflow.keras.preprocessing.sequence import pad_sequences
# pad_sequences has 3 parameters 1-input ,2= max-padding-length , 3 -pre-padding/post-paddind
padded_input_sequences = pad_sequences(input_sequence , maxlen = max_len , padding = 'pre')
padded_input_sequences

array([[  0,   0,   0, ...,   0,  93,   1],
       [  0,   0,   0, ...,  93,   1,  13],
       [  0,   0,   0, ...,   0,  11,   7],
       ...,
       [  0,   0,   0, ..., 279,  18, 280],
       [  0,   0,   0, ...,  18, 280, 281],
       [  0,   0,   0, ..., 280, 281, 282]])

In [37]:
# separate the Input and Output   
# E.g. [  0,   0,   0, ...,   0,  93,   1], input=[  0,   0,   0, ...,   0,  93], output=[  1],
# E.g. [  0,   0,   0, ..., 279,  18, 280], input=[  0,   0,   0, ..., 279,  18], output=[ 280],

X = padded_input_sequences[: , : -1]
X


array([[  0,   0,   0, ...,   0,   0,  93],
       [  0,   0,   0, ...,   0,  93,   1],
       [  0,   0,   0, ...,   0,   0,  11],
       ...,
       [  0,   0,   0, ...,   0, 279,  18],
       [  0,   0,   0, ..., 279,  18, 280],
       [  0,   0,   0, ...,  18, 280, 281]])

In [38]:
Y = padded_input_sequences[: , -1]
Y


array([  1,  13,   7,   1,  12,  42,  15,  43,  53,  68,  13, 147, 148,
        12,  94,   5,  44,  29,  95,  30,   2,   8,   4,  26,  44,  69,
         6,  31,  70,  45,   7,   1,  71,  72,   6,   1,  12,  71,  72,
         6,   1,  12,   7,  54,  73,  32,   1,  71,  12,  42, 149,  70,
        54,  31,  55, 150,   7,   1,  96,   6,   1,  68,  13,   9,  19,
       151,   1, 152, 153, 154, 155,  15,  43,  53, 156,  15,  43,  53,
        15, 159,  74, 160,  98,  99,  10, 163,   1, 164,  96,  76,  77,
       100,  33,  14, 165,  33,  43,  53,  68,  13, 166, 101,  74,  20,
       102,  19,   5,  78,   6,  21,  13, 102,  20, 101,  74, 167,  56,
        46,   5,  78,   6,  21, 168, 169,  22,   3, 104,   5, 105,  34,
         9,   3,  47,   5, 106,   6,   1,  34,  16,  35,  17,  56, 170,
        32, 107,  22,   2, 104,   5,  34,   2,  10, 171, 172,  20,  57,
         1, 106,  10,   3, 173,   1, 108, 174,  21,  58, 176,   4,  79,
        45,  59,  45, 109, 177,   6,   1,  12,  77, 178,  58,  6

In [39]:
X.shape

(863, 56)

In [40]:
Y.shape

(863,)

In [41]:
# total number of words
vocab_size= len(tokenizer.word_index)
vocab_size

282

In [42]:
# make the one-hot-Encoding of Y,,because Y is scaller 
from tensorflow.keras.utils import to_categorical
Y = to_categorical(Y , num_classes = 283)                 # words_total=282,we add 283 because the Hot-vector starts from the 0

In [43]:
Y.shape
Y

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [44]:
# import layers

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM,  Dense

# Model 

In [81]:
#   Model Define
input_length= 56
embedding_dim = 100
vocab_size = 283

model= Sequential()
#model.add(Embedding(input_dim = vocab_size, output_dim = embedding_dim, input_length=56)) 
model.add(Embedding(283, 100, input_length=56)) 

# Embedding(Total_vocabulary_words, embedding_shape/output_dense_vector , total_words_in_every_row)

model.add(LSTM(150,  return_sequences=False))                                              # 150 nodes in LSTM_gate
model.add(Dense(vocab_size, activation = 'softmax'))                         #Dense(neurons must equal to total words in Vocavularly)


283


# Build Model

In [83]:
 # Build the Model
model.build(input_shape=(None, input_length))  # Define batch size and input length explicitly
                                               # None means the batch size can vary, 56 features per input

# Compile Model

In [85]:
#  Compile model

model.compile(loss='categorical_crossentropy', optimizer= 'adam', metrics = ['accuracy'])

# Model Summary

In [87]:
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)         │ (None, 56, 100)        │        28,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_8 (LSTM)                   │ (None, 150)            │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 283)            │        42,733 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 221,633 (865.75 KB)

 Trainable params: 221,633 (865.75 KB)

 Non-trainable params: 0 (0.00 B)

In [89]:
# Model Fitting
model.fit(X, Y, epochs=100)

Epoch 1/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 9s 83ms/step - accuracy: 0.0512 - loss: 5.5491
Epoch 2/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 52ms/step - accuracy: 0.0711 - loss: 5.0708
Epoch 3/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.0675 - loss: 5.0286
Epoch 4/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 3s 66ms/step - accuracy: 0.0730 - loss: 4.9259
Epoch 5/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 56ms/step - accuracy: 0.0843 - loss: 4.9363
Epoch 6/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 54ms/step - accuracy: 0.0945 - loss: 4.8014
Epoch 7/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.1173 - loss: 4.5817
Epoch 8/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.1285 - loss: 4.3797
Epoch 9/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.1622 - loss: 4.1810
Epoch 10/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 54ms/step - accuracy: 0.2033 - loss: 4.0017
Epoch 11/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.2220 - loss: 3.8411
Epoch 12/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step

# Prediction of Model

In [119]:
# Test

text = "mail"
#   3-steps for word  -Tokenizer -padding  -predict

# Tokenizer
token_text = tokenizer.texts_to_sequences([text])[0]

# padding
padded_token_text = pad_sequences([token_text], maxlen= 56, padding='pre')

# predict             send padded_token_text to the model
model.predict(padded_token_text)                         # it returns the all words probablity



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step


array([[8.98007875e-06, 8.91370641e-04, 1.08100830e-04, 2.43038121e-05,
        1.61315706e-02, 3.94926034e-03, 4.98599897e-04, 6.82422705e-03,
        5.22646587e-04, 2.24698422e-04, 4.46630962e-04, 7.28507948e-05,
        3.30123794e-03, 1.11297611e-03, 3.18315142e-04, 4.07356732e-02,
        1.30894575e-02, 8.70013516e-03, 6.96665375e-03, 7.30263637e-05,
        3.11545865e-03, 5.43682277e-02, 7.52346881e-04, 7.56048830e-05,
        2.34509978e-04, 7.53783272e-04, 7.52161082e-04, 7.61220057e-04,
        7.48712191e-05, 3.57149431e-04, 5.25879586e-05, 3.18491569e-04,
        2.62443675e-04, 5.59247390e-04, 1.28160624e-04, 3.04330816e-03,
        6.52678264e-03, 9.41978360e-05, 1.51539556e-04, 2.73276528e-04,
        5.25972064e-05, 6.10341434e-04, 1.04520738e-03, 2.29746872e-03,
        1.51910270e-02, 2.88416952e-04, 2.01024152e-02, 2.26756616e-04,
        6.74031890e-06, 3.20680290e-02, 3.10117062e-02, 5.05813514e-04,
        8.72472228e-05, 6.09876309e-03, 2.42890194e-02, 1.375236

In [113]:
#  now from all words probablities, we choose Highest

import numpy as np
pos = np.argmax(model.predict(padded_token_text))
print(pos)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
112


In [117]:
for word, index in tokenizer.word_index.items():
 if index == pos:
    print(word)

absolutely


In [152]:
# Now we hav to find 5 words,we will use loop
import time
text = "come for "

for i in range(5):
    token_text = tokenizer.texts_to_sequences([text])[0]

    # padding
    padded_token_text = pad_sequences([token_text], maxlen= 56, padding='pre')

    # predict             send padded_token_text to the model
    pos = np.argmax(model.predict(padded_token_text))                   # it returns the all words probablity

    for word, index in tokenizer.word_index.items():
     if index == pos:
        text= text + " " + word 
        print(text)
        time.sleep(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
come for  machine
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
come for  machine learning
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
come for  machine learning and
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
come for  machine learning and deep
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
come for  machine learning and deep learning
